### ISSUE TITLE
Add Graph Studio section

### ISSUE THREAD

**Issue by ryotayamanaka** [ryotayamanaka/shortest-path#2]
Also need Graph Studio screenshots

**Comment by ryotayamanaka** [comment]
d74e51c7 - Added Graph Studio section at the bottom of the README

**Comment by Mikerquan** [comment]
![image](https://user-images.githubusercontent.com/22470602/114273692-ac5f0600-9a4d-11eb-9c29-236a765c87ee.png)

**Comment by Mikerquan** [comment]
%pgql-pgx

SELECT a.name AS a, b.name AS b, COUNT(e) AS path_length, SUM(e.cost) AS total_cost, ARRAY_AGG(n.name) AS nodes

FROM MATCH TOP 3 SHORTEST ((a)(-[e]->(n))*(b)) ON ROUTE01

WHERE a.name='A'AND b.name='H'

**Comment by ryotayamanaka** [comment]
Thank you @shengjunquan for PR #9
